# Generated by Django 4.0.1 on 2022-01-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Node Name')),
                ('type', models.CharField(max_length=255, verbose_name='Node Type')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='Node IP Address')),
                ('last_block', models.IntegerField(verbose_name='Node Last Block')),
                ('pending_transactions', models.IntegerField(verbose_name='Node Pending Transactions')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
    ]
