# Generated by Django 4.0.1 on 2022-01-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'Whitelist',
                'verbose_name_plural': 'Whitelist',
            },
        ),
    ]
